#-------------------------------
# General Site Settings
baseURL = "http://calebmallen.com/"
languageCode = "en-us"
googleAnalytics = "G-QP775XWP96"
paginate = 9


[params]
  logo = "/images/logo.png"
  logo_dark = "/images/logo-dark.png"
  author = "Caleb Allen"
  description = "Storyteller & Illustrator"


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "work"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact/"
    weight = 4

  [[menu.main]]
    identifier = "Newsletter"
    name = "newsletter"
    url = "/newsletter/"
    weight = 3

  #-------------------------------
  # Portfolio Settings
  [params.portfolio]

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-Cover.jpg"

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-EndPages.jpg"

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-WhatsInside.jpg"

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-HungryDuck.jpg"
   
  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-LonelyFlowers.jpg"

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-OpenBox.jpg"

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-GustofWind.jpg"

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-CatchIt.jpg"

  [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-JumpandReach.jpg"

    [[params.gallery_item]]
    image = "/images/Fox-CalebAllen-LostbutOk.jpg"

    [[params.gallery_item]]
    image = "/images/Duck-CalebAllen-DUCK.jpg"

    [[params.gallery_item]]
    image = "/images/Duck-CalebAllen-AliveWater.jpg"

    [[params.gallery_item]]
    image = "/images/Rabbit-CalebAllen-RabbitWorry.jpg"

    [[params.gallery_item]]
    image = "/images/Rabbit-CalebAllen-Chirp.jpg"

    [[params.gallery_item]]
    image = "/images/Rabbit-Caleb-Allen-IveSlipped.jpg"

    [[params.gallery_item]]
    image = "/images/Bear-CalebAllen-MoonLept.jpg"


  #-------------------------------
  # Footer Settings
  [[params.social]]
    icon = "ion-logo-instagram"
    link = "https://www.instagram.com/caleb.mallen/"
    color = "#000000"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false